// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX80rl_PnrFrg0yDFjdfvjO_JjgrVa6Nw',
    appId: '1:153476063751:web:181f19636c516cba07c0a2',
    messagingSenderId: '153476063751',
    projectId: 'nyxra-ai-shamii',
    authDomain: 'nyxra-ai-shamii.firebaseapp.com',
    storageBucket: 'nyxra-ai-shamii.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV4y4gf1qIb_ZNsMTh4NbTnGizK_P5YQI',
    appId: '1:153476063751:android:2262253f03799a6e07c0a2',
    messagingSenderId: '153476063751',
    projectId: 'nyxra-ai-shamii',
    storageBucket: 'nyxra-ai-shamii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX80rl_PnrFrg0yDFjdfvjO_JjgrVa6Nw',
    appId: '1:153476063751:ios:181f19636c516cba07c0a2',
    messagingSenderId: '153476063751',
    projectId: 'nyxra-ai-shamii',
    storageBucket: 'nyxra-ai-shamii.firebasestorage.app',
    iosBundleId: 'com.nyxra.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX80rl_PnrFrg0yDFjdfvjO_JjgrVa6Nw',
    appId: '1:153476063751:ios:181f19636c516cba07c0a2',
    messagingSenderId: '153476063751',
    projectId: 'nyxra-ai-shamii',
    storageBucket: 'nyxra-ai-shamii.firebasestorage.app',
    iosBundleId: 'com.nyxra.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX80rl_PnrFrg0yDFjdfvjO_JjgrVa6Nw',
    appId: '1:153476063751:web:181f19636c516cba07c0a2',
    messagingSenderId: '153476063751',
    projectId: 'nyxra-ai-shamii',
    authDomain: 'nyxra-ai-shamii.firebaseapp.com',
    storageBucket: 'nyxra-ai-shamii.firebasestorage.app',
  );
}
